# Generated by Django 5.2.1 on 2025-07-06 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_cart_alter_product_popularity_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
